version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5000:5000"
    networks:
      - prueba-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: prueba-backend
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - DB_HOST=mysql
      - DB_NAME=${DB_NAME}
      - DB_USER=root
      - DB_PASSWORD=${DB_PASSWORD}
      - SOAP_ENDPOINT=${SOAP_ENDPOINT}
      - SOAP_USER=${SOAP_USER}
      - SOAP_PASSWORD=${SOAP_PASSWORD}
      - SOAP_FLEET_ID=${SOAP_FLEET_ID}
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
      - /app/node_modules
    networks:
      - prueba-network
    restart: unless-stopped

  frontend:
    build: ./client
    dockerfile: Dockerfile
    container_name: prueba-frontend
    environment:
      - REACT_APP_API_URL=http://localhost:4001
    ports:
      - "4001:4001"
    volumes:
      - ./client:/app
      - /app/node_modules
    networks:
      - prueba-network
    restart: unless-stopped

volumes:
  mysql_data:

networks:
  prueba-network:
    driver: bridge